version: "3"
services:
    mysql:
        image: mariadb:10.4
        volumes:
            - "./data/db:/var/lib/mysql"
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
    core:
        build: ./dockerfiles
        depends_on:
            - mysql
        volumes:
            - ".:/var/www"

    nginx:
        image: nginx:latest
        depends_on:
            - core
        volumes:
            - ".:/var/www"
            - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"
        restart: always
